-- Local-only Backend-compatible fixture schema.
-- This is not a production migration and contains no credentials.

DROP TABLE IF EXISTS demand CASCADE;
DROP TABLE IF EXISTS product_catalog CASCADE;
DROP TABLE IF EXISTS category CASCADE;

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES category(id),
    name VARCHAR(50) NOT NULL,
    depth SMALLINT NOT NULL,
    facet TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (parent_id, name)
);

CREATE TABLE product_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key VARCHAR(200) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    category_id BIGINT NOT NULL REFERENCES category(id),
    spec_summary VARCHAR(500),
    list_price INTEGER,
    thumbnail_url VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE demand (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key VARCHAR(200) NOT NULL UNIQUE,
    demand_board_id BIGINT,
    member_id BIGINT NOT NULL DEFAULT 1,
    catalog_id BIGINT NOT NULL REFERENCES product_catalog(id),
    desired_price_max INTEGER NOT NULL,
    desired_price_min INTEGER NOT NULL,
    desire_end_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '7 days'),
    quantity INTEGER NOT NULL,
    extra_requirement VARCHAR(200),
    is_substitutable BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'UNASSIGNED',
    label VARCHAR(200),
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_local_demand_unprocessed ON demand (processed_at, id);
